"""Auto-generated module docstring for portfolio\migrations\0001_initial.py.

This docstring was added by scripts/add_docstrings.py.
"""

# Generated by Django 6.0.4 on 2026-04-14 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Auto-generated docstring for class Migration.

    Returns:
        Description.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('config', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='portfolio.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('timeline', models.CharField(max_length=100)),
                ('order', models.FloatField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.FloatField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.FloatField()),
                ('is_visible', models.BooleanField(default=True)),
                ('presentation', models.JSONField(default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIST', 'List'), ('GRID', 'Grid'), ('TIMELINE', 'Timeline'), ('KEY_VALUE', 'Key Value'), ('IMAGE', 'Image')], max_length=50)),
                ('order', models.FloatField()),
                ('config', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='portfolio.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('order', models.FloatField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('data_source', models.CharField(choices=[('PORTFOLIO', 'Portfolio'), ('PROJECT', 'Project'), ('SKILL', 'Skill'), ('EXPERIENCE', 'Experience')], max_length=50)),
                ('field', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('github_url', 'Github'), ('image', 'Image'), ('name', 'Name'), ('level', 'Level'), ('company', 'Company'), ('role', 'Role'), ('timeline', 'Timeline')], max_length=50)),
                ('order', models.FloatField()),
                ('is_visible', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='portfolio.block')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['block'], name='portfolio_e_block_i_3b8451_idx'), models.Index(fields=['block', 'order'], name='portfolio_e_block_i_07ab8a_idx')],
                'unique_together': {('block', 'data_source', 'field')},
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['portfolio'], name='portfolio_s_portfol_75d6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['portfolio', 'order'], name='portfolio_s_portfol_b9fc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['section'], name='portfolio_b_section_adb117_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['section', 'order'], name='portfolio_b_section_61734b_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='portfolio_p_user_id_24fc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_a92ff2_idx'),
        ),
    ]
