"""Auto-generated module docstring for portfolio\migrations\0002_alter_project_image.py.

This docstring was added by scripts/add_docstrings.py.
"""

# Generated by Django 6.0.4 on 2026-04-14 13:00

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):
    """Auto-generated docstring for class Migration.

    Returns:
        Description.
    """

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.user_directory_path_for_project_images),
        ),
    ]
