# Generated by Django 6.0.4 on 2026-04-14 13:00

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.user_directory_path_for_project_images),
        ),
    ]
