"""Auto-generated module docstring for portfolio\migrations\0003_rename_presentation_section_config_element_config_and_more.py.

This docstring was added by scripts/add_docstrings.py.
"""

# Generated by Django 6.0.4 on 2026-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    """Auto-generated docstring for class Migration.

    Returns:
        Description.
    """

    dependencies = [
        ('portfolio', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='presentation',
            new_name='config',
        ),
        migrations.AddField(
            model_name='element',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
