"""Auto-generated module docstring for portfolio\migrations\0004_portfolio_description.py.

This docstring was added by scripts/add_docstrings.py.
"""

# Generated by Django 6.0.4 on 2026-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """Auto-generated docstring for class Migration.

    Returns:
        Description.
    """

    dependencies = [
        ('portfolio', '0003_rename_presentation_section_config_element_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
