"""Auto-generated module docstring for portfolio\migrations\0005_portfolio_user_slug_unique_and_theme_optional.py.

This docstring was added by scripts/add_docstrings.py.
"""

# Generated by GitHub Copilot on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Auto-generated docstring for class Migration.

    Returns:
        Description.
    """

    dependencies = [
        ("portfolio", "0004_portfolio_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portfolios",
                to="portfolio.theme",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"),
                name="uniq_portfolio_user_slug",
            ),
        ),
    ]
