"""Auto-generated module docstring for portfolio\migrations\0009_alter_element_field.py.

This docstring was added by scripts/add_docstrings.py.
"""

# Generated by Django 6.0.4 on 2026-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    """Auto-generated docstring for class Migration.

    Returns:
        Description.
    """

    dependencies = [
        ('portfolio', '0008_portfolio_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='field',
            field=models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('resume', 'Resume'), ('github_url', 'Github'), ('image', 'Image'), ('name', 'Name'), ('level', 'Level'), ('company', 'Company'), ('role', 'Role'), ('timeline', 'Timeline')], max_length=50),
        ),
    ]
