# Generated by Django 6.0.1 on 2026-04-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_resumeupload'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portfoliotemplate',
            new_name='portfolio_p_is_acti_a648cb_idx',
            old_name='portfolio_p_is_acti_77effd_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeupload',
            new_name='portfolio_r_user_id_bfd9f4_idx',
            old_name='portfolio_r_user_id_13e6b2_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeupload',
            new_name='portfolio_r_portfol_c571f4_idx',
            old_name='portfolio_r_portfol_89fdb4_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeupload',
            new_name='portfolio_r_status_7c02d8_idx',
            old_name='portfolio_r_status_d341de_idx',
        ),
    ]
